version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "50007:50007"
      - "8501:8501"
    environment:
      - USE_LOCALSTACK=1
      - DOCKERHUB_USER=ohtuprojtinymlaas
      - DOCKERHUB_PASSWORD=AJHDI.A76a5d-gnxjaah
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  # hello_world:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SKIP_SSL_CERT_DOWNLOAD=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
