version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "50007:50007"
      - "8501:8501"
    environment:
      - USE_LOCALSTACK=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: backend/
    ports:
      - "8080:8080"

  hello_world:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

  image_sender:
    restart: always
    build:
      context: .
      dockerfile: image_sender.Dockerfile

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SKIP_SSL_CERT_DOWNLOAD=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
