version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - USE_LOCALSTACK=1
      - AWS_ACCESS_KEY_ID=<your_access_key>
      - AWS_SECRET_ACCESS_KEY=<your_secret_key>
      - DOCKERHUB_USER=<your_dockerhub_user>
      - DOCKERHUB_PASSWORD=<your_dockerhub_password>
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SKIP_SSL_CERT_DOWNLOAD=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
