name: CI

on:
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Build Dockerfile
    #   run: make docker
    # - name: Run Dockerfile
    #   run: docker run -d hello_world
    # - name: Copy coverage files
    #   run: CONTAINER_ID=$(sudo docker ps -aql) && docker cp $CONTAINER_ID:/tflite-micro ./tflite-micro
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with coverage
      run: |
        coverage run --source=. -m pytest
    - name: Generate coverage report
      run: coverage report -m
    - name: Save coverage data
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: .coverage
    - name: Run WebApp
      run: docker-compose up --build -d
    - name: Run Robot Framework tests
      run: robot pages/tests/ 
    - name: Get Robot Coverage
      run: |
        CONTAINER=$(docker-compose ps -q frontend)
        docker stop $CONTAINER
        docker cp $CONTAINER:/app/.coverage .coverage.robotframework
    - name: Combine coverage
      run: python3 -m coverage combine
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: .coverage
        token: ${{ secrets.CODECOV_TOKEN }}
